export { default as Home } from "@/views/Home.vue"
export { default as Login } from "@/views/Login.vue"
export { default as About } from "@/views/About.vue"
export { default as Register } from "@/views/Register.vue"
export { default as Administration } from "@/views/Administration.vue"
